### PR TITLE
Added to topics

### PR DESCRIPTION
**Pull request by dolly-d**
### Description
Added entry #15, Maximum Subarray, Leetcode

### Checklist
- [ x] Made sure my content contribution was publicly accessible and free
- [x ] Code or Yaml content compiles correctly
- [ ] Created tests (if possible, topic contributions don't need tests)
- [x ] Added myself to the Contributors list on the README.md file

### CODE REVIEW

**Review by KGmajor — CHANGES_REQUESTED** [review]
Hi! Thank you for your PR. We had two other merges in before yours so please update your branch and resolve the conflicts. I think your entry should be # 17 on the topics.yaml.

**Comment by dolly-d** [comment]
Okay will do !

**Comment by dolly-d** [comment]
Updated my entry, thanks!

**Comment by KGmajor** [comment]
I fixed some trailing spaces and it's good to go. Thank you!

**Pull request merged**
