### PR TITLE
added topic 15 from projectEuler

### PR DESCRIPTION
**Pull request by sieis**
### Description
Added Topic 15 to the topics yaml. Rejoice!

### Checklist
- [x] Made sure my content contribution was publicly accessible and free
- [x] Code or Yaml content compiles correctly
- [ ] Created tests (if possible, topic contributions don't need tests)
- [x] Added myself to the Contributors list on the README.md file

### CODE REVIEW

**Review by KGmajor — CHANGES_REQUESTED** [review]
Hi! Yaml linter left a suggestion on line length. We can merge after adjustment.

**Review by sieis — COMMENTED** [review]
Corrected line length error from yaml test

**Comment by sieis** [comment]
...aaaaand, fixed those trailing spaces too 😄

**Comment by KGmajor** [comment]
Looks good, thank you!

**Pull request merged**
